name: 'Lenovo Auto Signin'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '50 16 * * *'

jobs:
  auto_signin:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4
      - name: 'Signin'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
        run: python main.py
